apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-app
  labels:
    app: appointment-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointment-app
  template:
    metadata:
      labels:
        app: appointment-app
    spec:
      containers:
        - name: my-app-appointment
          image: halelaacr.azurecr.io/patient/appointment-svc:latest
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-app
spec:
  type: ClusterIP
  selector:
    app: appointment-app
  ports:
    - port: 80
      targetPort: 3001
